### ISSUE TITLE
Plot seismicity against observed deformation.

### ISSUE THREAD

**Issue by nackerley** [Volcano-Risk-Reduction-in-Canada/Volcanic-Interpretation-Workbench#25]
The assessment of the state of unrest of a volcano is complex, and to be accurate must involve multiple kinds of data. This user story specifically relates to seismicity near the volcano. Users such as analysts and vulcanologists will want to be able to visualize the spatial relationship between detected seismic events and observed deformation.

It would be relatively simple to query the CHIS FDSNWS for earthquakes near an AoI in a given time range. Most useful would be to plot them against the observed deformation, typically as circles with radius proportional to magnitude, and ideallly also showing epicentral uncertainty ellipses.

CHIS has a "mock" FDSNWS running currently, where you can see what the results could look like: https://earthquakescanada.nrcan.gc.ca/stndon/NEDB-BNDS/bulletin-en.php?display=1&limit=4001&eventtype=L&latitude=50.63&longitude=-123.50&maxradius=1&starttime=2000-01-01T00%3A00%3A00&endtime=2023-03-12T00%3A00%3A00&format=text
(This "text" format contains no information about epicentral ellipses; for that you would need to request QuakeML and is not currently supported).

**Comment by drotheram** [comment]
- show recent earthquakes:
- All earthquakes within:
    - 50km
    - 2 years
    - any magnitude
    
Potentially query FDSNWS

**Comment by mssond** [comment]
This issue was resolved by PR #63
