### ISSUE TITLE
Represent coherence matrix as timedeltas vs datetimes

### ISSUE THREAD

**Issue by nackerley** [Volcano-Risk-Reduction-in-Canada/Volcanic-Interpretation-Workbench#4]
Currently the coherence matrix display wastes a lot of wasted space in the off-diagonals. Datetime pairs below the diagonal are completely redundant, but most datetime pairs above the diagonal are also not useful because there is typically low coherence between pairs which differ by more than a few weeks. Because of the wasted space, the user typically has to zoom in quite a bit to see patterns or to select a specific pixel.

An improved visualization would be obtained by representing coherence matrix with datetime (typically just the date) of the newer image in the pair on the horizontal axis vs the timedelta to the older image in the pair on the vertical axis (typically in days). Furthermore if we're only interested in datetime pairs at +/- weeks and +/- years, we can entirely drop pixels which will never be populated.

Since we probably want square pixels, this will result in a representation which is much wider than it is tall. This may work well with #3. This would also enable the addition of a scroll bar to control the newer image date while maintaining a constant timedelta.

@drotheram if you could attach a file containing the coherence matrix (both the data and the x and y axis datetimes) for Meager_5M3 here, I could generate a mock-up of an improved visualization.

**Comment by drotheram** [comment]
[CoherenceMatrix.csv](https://github.com/Volcano-Risk-Reduction-in-Canada/Volcanic-Interpretation-Workbench/files/10460396/CoherenceMatrix.csv)

**Comment by nackerley** [comment]
@drotheram can you try dumping the data again? This looks like the data from the top-right corner of Meager_5M3 (below), but I inspected the file and there are only 25 lines that don't end in a comma - I think a lot of data is missing.

![Image](https://user-images.githubusercontent.com/14931979/217890881-7872a62a-bb81-458f-9416-b8c7e02444f9.png)

**Comment by nackerley** [comment]
Here's what I can do with the data you've provided:
![DashboardCoherence_DateVsDate](https://user-images.githubusercontent.com/14931979/217905886-6e7b780b-83dd-4a9e-8667-1407d37642f9.png)
![DashboardCoherence_DeltaVsDate](https://user-images.githubusercontent.com/14931979/217905896-98b1c8ff-3c36-4c2e-b0e1-25f7961a09fa.png)

**Comment by drotheram** [comment]
[CoherenceMatrix.csv](https://github.com/Volcano-Risk-Reduction-in-Canada/Volcanic-Interpretation-Workbench/files/10700702/CoherenceMatrix.csv)
Here's the coherence matrix for Edgecumbe

**Comment by drotheram** [comment]
[Uploading CoherenceMatrix (1).csv…]()
And here is Meager 5M3

**Comment by nackerley** [comment]
Ok, so this is a pretty good example, now. 
![CoherenceMatrixMeager5M3_DateVsDate](https://user-images.githubusercontent.com/14931979/217932696-9d71303d-4891-4344-b6ca-d6b12acf07ad.png)
![CoherenceMatrixMeager5M3_DeltaVsDate](https://user-images.githubusercontent.com/14931979/217932715-25bb014e-7700-4ebb-9fcc-597218319ea3.png)

There's not much improvement with the Edgecumbe example, because the date ranges are small and not as sparse.

**Comment by nackerley** [comment]
Ok, here's a "final" prototype where I've tweaked the subplot axes heights to be in proportion to the amount of data, and implemented a proposed fixed colorbar for coherence:
- 'plasma' between 0.25 and 0.75
- dark grey below 0.25
- white above 0.75
We can adjust the colormap and cutoffs, but the idea is to use a perceptually uniform colormap for the most meaningful part of the range, and take advantage of the "extend" feature to note outliers from that range.

```python
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

CMAP = plt.get_cmap('plasma')
CMAP.set_extremes(under='0.2', over='white')
NORM = Normalize(0.25, 0.75)
```

![CoherenceMatrixMeager5M3_DateVsDate](https://user-images.githubusercontent.com/14931979/217953984-47005aeb-98cd-42d0-94f5-dd76a4f7cf60.png)
![CoherenceMatrixMeager5M3_DeltaVsDate](https://user-images.githubusercontent.com/14931979/217953994-c81951eb-104e-42a5-927a-1dfc09111176.png)
